name: Generate index.json

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  generate-index:
    runs-on: ubuntu-latest
    outputs:
      years: ${{ steps.collect-years.outputs.years }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Optional debug
      - name: List scripts dir (debug)
        run: ls -la scripts || true

      - name: Build country/global indexes
        run: node scripts/build-indexes.js

      # Optional debug
      - name: Show data tree (debug)
        run: |
          echo "---- data/ ----"
          find data -maxdepth 3 -type f | sort || true

      - id: collect-years
        name: Collect years (Node)
        run: |
          node -e "const fs=require('fs'),path=require('path');
          const root='data', years=new Set();
          if(fs.existsSync(root)){
            for(const cc of fs.readdirSync(root)){
              if(!/^[a-z]{2}$/i.test(cc)) continue;
              const cdir=path.join(root,cc);
              if(!fs.statSync(cdir).isDirectory()) continue;
              for(const y of fs.readdirSync(cdir)){
                if(!/^\d{4}$/.test(y)) continue;
                const ydir=path.join(cdir,y);
                if(!fs.existsSync(path.join(ydir,'data.json'))) continue;
                if(!fs.existsSync(path.join(ydir,'rates.json'))) continue;
                years.add(Number(y));
              }
            }
          }
          const arr=[...years].sort((a,b)=>a-b);
          require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `years=${JSON.stringify(arr)}\n`);
          console.log('Matrix years:', JSON.stringify(arr));"

      - name: Commit and push index changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: auto-generate index.json"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD

  build-world-matrix:
    if: ${{ needs.generate-index.outputs.years != '[]' && needs.generate-index.outputs.years != '' }}
    runs-on: ubuntu-latest
    needs: generate-index
    strategy:
      fail-fast: false
      matrix:
        year: ${{ fromJson(needs.generate-index.outputs.years) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build world for a single year
        run: node scripts/build-world-year.js ${{ matrix.year }}

      - name: Upload world artifact for this year
        uses: actions/upload-artifact@v4
        with:
          name: world-${{ matrix.year }}
          path: |
            data/world/${{ matrix.year }}/data.json
            data/world/index.json
          if-no-files-found: error

  merge-world-and-commit:
    runs-on: ubuntu-latest
    needs: build-world-matrix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all world artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge artifacts into repo
        shell: bash
        run: |
          shopt -s globstar nullglob
          # copy per-year world data
          for f in artifacts/world-*/data/world/*/data.json; do
            year=$(echo "$f" | sed -nE 's#artifacts/world-([0-9]{4})/.*#\1#p')
            mkdir -p "data/world/$year"
            cp "$f" "data/world/$year/data.json"
          done
          # update world/index.json (from any artifact; they all include it)
          lastIndex=$(ls -d artifacts/world-*/ 2>/dev/null | tail -n 1)
          if [ -n "$lastIndex" ] && [ -f "${lastIndex}data/world/index.json" ]; then
            mkdir -p data/world
            cp "${lastIndex}data/world/index.json" data/world/index.json
          fi

      - name: Commit and push world changes (single commit)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/world
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: build world aggregates (matrix)"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD
