name: Build index + world

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: List scripts dir (debug)
        run: ls -la scripts || true

      - name: Build country/global indexes
        run: node scripts/build-indexes.js

      - name: Show data tree (debug)
        run: |
          echo "---- data/ (after indexes) ----"
          find data -maxdepth 3 -type f | sort || true

      - name: Commit and push index changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: auto-build index.json"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD

  build-world:
    needs: build-index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build world (all detected years)
        run: node scripts/build-world.js

      # --- diagnostics to verify the file actually exists and changed ---
      - name: Print world 2025 (debug)
        run: |
          echo "---- data/world/2025/data.json (post-build) ----"
          test -f data/world/2025/data.json && head -c 400 data/world/2025/data.json && echo || echo "missing"

      - name: Check if ignored (debug)
        run: |
          echo "---- .gitignore check ----"
          cat .gitignore || true
          git check-ignore -v data/world/2025/data.json || echo "not ignored"

      - name: Commit and push world changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/world
          git status --porcelain
          git diff --cached --name-only || true
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: build world aggregates"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD
